name: Reusable swap functional tests

on:
  workflow_call:
    inputs:
      repo_for_exchange:
        required: false
        default: 'LedgerHQ/app-exchange'
        type: string
      branch_for_exchange:
        required: false
        default: 'develop'
        type: string
      branch_for_tezos:
        required: false
        default: 'main'
        type: string
      branch_for_ethereum:
        required: false
        default: 'develop'
        type: string
      run_for_devices:
        description: 'The list of device(s) on which the test will run (defaults to ["nanos", "nanox", "nanosp", "stax"])'
        required: false
        default: '["nanos", "nanox", "nanosp", "stax"]'
        type: string
      test_filter:
        required: false
        default: '""'
        type: string

jobs:
  build_sideloaded_applications:
    name: Build sideloaded applications using the reusable workflow
    strategy:
      fail-fast: false
      matrix:
        coin:
        - name: tezos_new
          repo: trilitech/ledger-app-tezos-wallet
          branch: ${{ inputs.branch_for_tezos }}
          relative_app_directory: 'app'
        - name: ethereum
          repo: LedgerHQ/app-ethereum
          branch: ${{ inputs.branch_for_ethereum }}
          relative_app_directory: '.'

    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      app_repository: ${{ matrix.coin.repo }}
      app_branch_name: ${{ matrix.coin.branch }}
      relative_app_directory: ${{ matrix.coin.relative_app_directory }}
      flags: "COIN=${{ matrix.coin.name }} CHAIN=${{ matrix.coin.name }} DEBUG=1"
      upload_app_binaries_artifact: libraries_binaries
      upload_as_lib_artifact: ${{ matrix.coin.name }}

  build_exchange_application:
    name: Build application using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      app_repository: ${{ inputs.repo_for_exchange }}
      app_branch_name: ${{ inputs.branch_for_exchange }}
      flags: "TESTING=1 TEST_PUBLIC_KEY=1 DEBUG=1"
      upload_app_binaries_artifact: exchange_binaries

  ragger_tests:
    name: Run ragger tests using the reusable workflow
    needs:
      - build_exchange_application
      - build_sideloaded_applications
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_ragger_tests.yml@v1
    with:
      app_repository: ${{ inputs.repo_for_exchange }}
      app_branch_name: ${{ inputs.branch_for_exchange }}
      download_app_binaries_artifact: exchange_binaries
      lib_binaries_artifact: libraries_binaries
      test_dir: test/python
      run_for_devices: ${{ inputs.run_for_devices }}
      test_filter: ${{ inputs.test_filter }}
